<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\UMKM;
use App\Models\Kecamatan;
use App\Models\Desa;
use App\Models\Subsektor;

class UMKMSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get IDs for relationships
        $kecamatanIds = Kecamatan::pluck('id')->toArray();
        $desaIds = Desa::pluck('id')->toArray();
        $subsektorIds = Subsektor::pluck('id')->toArray();

        // Sample UMKM data
        $umkms = [
            [
                'nama_usaha' => 'Tenun Tradisional Muna Barat',
                'nama_pemilik' => 'Siti Rahayu',
                'subsektor_id' => $subsektorIds[array_rand($subsektorIds)],
                'alamat_usaha' => 'Jl. Raya Barangka No. 123',
                'kecamatan_id' => $kecamatanIds[array_rand($kecamatanIds)],
                'desa_id' => $desaIds[array_rand($desaIds)],
                'tahun_berdiri' => 2015,
                'jumlah_tenaga_kerja' => 8,
                'omset_tahun' => 150000000,
                'no_telp' => '6281234567890',
                'email' => 'tenunmuna@example.com',
                'jenis_badan_usaha' => 'Perseorangan',
                'jenis_hki' => 'Hak Cipta',
                'nib' => '123456789012345',
                'facebook' => 'https://facebook.com/tenunmuna',
                'instagram' => 'https://instagram.com/tenunmuna',
                'tiktok' => 'https://tiktok.com/@tenunmuna',
                'whatsapp' => 'https://wa.me/6281234567890',
                'website' => 'https://tenunmuna.com',
                'latitude' => -5.1667,
                'longitude' => 122.6667,
                'deskripsi' => 'Kami memproduksi kain tenun tradisional khas Muna Barat dengan motif-motif yang indah dan bermakna budaya.',
                'status_aktif' => true,
                'status_verifikasi' => true,
                'views' => rand(100, 1000)
            ],
            [
                'nama_usaha' => 'Warung Kuliner Nusantara',
                'nama_pemilik' => 'Ahmad Suprianto',
                'subsektor_id' => $subsektorIds[array_rand($subsektorIds)],
                'alamat_usaha' => 'Jl. Poros Tiworo No. 45',
                'kecamatan_id' => $kecamatanIds[array_rand($kecamatanIds)],
                'desa_id' => $desaIds[array_rand($desaIds)],
                'tahun_berdiri' => 2018,
                'jumlah_tenaga_kerja' => 5,
                'omset_tahun' => 200000000,
                'no_telp' => '6281234567891',
                'email' => 'warungnusantara@example.com',
                'jenis_badan_usaha' => 'UD',
                'jenis_hki' => null,
                'nib' => '123456789012346',
                'facebook' => 'https://facebook.com/warungnusantara',
                'instagram' => 'https://instagram.com/warungnusantara',
                'tiktok' => 'https://tiktok.com/@warungnusantara',
                'whatsapp' => 'https://wa.me/6281234567891',
                'website' => null,
                'latitude' => -5.2000,
                'longitude' => 122.7000,
                'deskripsi' => 'Menyediakan berbagai makanan khas Nusantara dengan cita rasa otentik dan bahan-bahan segar.',
                'status_aktif' => true,
                'status_verifikasi' => true,
                'views' => rand(100, 1000)
            ],
            [
                'nama_usaha' => 'Meubel Kayu Jati Nusantara',
                'nama_pemilik' => 'Budi Santoso',
                'subsektor_id' => $subsektorIds[array_rand($subsektorIds)],
                'alamat_usaha' => 'Jl. Kayu Putih No. 78',
                'kecamatan_id' => $kecamatanIds[array_rand($kecamatanIds)],
                'desa_id' => $desaIds[array_rand($desaIds)],
                'tahun_berdiri' => 2012,
                'jumlah_tenaga_kerja' => 12,
                'omset_tahun' => 500000000,
                'no_telp' => '6281234567892',
                'email' => 'meubeljati@example.com',
                'jenis_badan_usaha' => 'CV',
                'jenis_hki' => null,
                'nib' => '123456789012347',
                'facebook' => 'https://facebook.com/meubeljati',
                'instagram' => 'https://instagram.com/meubeljati',
                'tiktok' => 'https://tiktok.com/@meubeljati',
                'whatsapp' => 'https://wa.me/6281234567892',
                'website' => 'https://meubeljati.com',
                'latitude' => -5.2333,
                'longitude' => 122.7333,
                'deskripsi' => 'Kami memproduksi meubel berkualitas tinggi dari kayu jati pilihan dengan desain yang elegan.',
                'status_aktif' => true,
                'status_verifikasi' => true,
                'views' => rand(100, 1000)
            ],
            [
                'nama_usaha' => 'Kerajinan Bambu Lestari',
                'nama_pemilik' => 'Dewi Kartika',
                'subsektor_id' => $subsektorIds[array_rand($subsektorIds)],
                'alamat_usaha' => 'Jl. Hijau Raya No. 23',
                'kecamatan_id' => $kecamatanIds[array_rand($kecamatanIds)],
                'desa_id' => $desaIds[array_rand($desaIds)],
                'tahun_berdiri' => 2017,
                'jumlah_tenaga_kerja' => 6,
                'omset_tahun' => 120000000,
                'no_telp' => '6281234567893',
                'email' => 'kerajinanbambu@example.com',
                'jenis_badan_usaha' => 'Perseorangan',
                'jenis_hki' => null,
                'nib' => '123456789012348',
                'facebook' => 'https://facebook.com/kerajinanbambu',
                'instagram' => 'https://instagram.com/kerajinanbambu',
                'tiktok' => 'https://tiktok.com/@kerajinanbambu',
                'whatsapp' => 'https://wa.me/6281234567893',
                'website' => null,
                'latitude' => -5.2667,
                'longitude' => 122.7667,
                'deskripsi' => 'Membuat berbagai kerajinan dari bambu yang ramah lingkungan dan estetik.',
                'status_aktif' => true,
                'status_verifikasi' => true,
                'views' => rand(100, 1000)
            ],
            [
                'nama_usaha' => 'Seni Tari Muna Kreatif',
                'nama_pemilik' => 'Agus Prasetyo',
                'subsektor_id' => $subsektorIds[array_rand($subsektorIds)],
                'alamat_usaha' => 'Jl. Seni No. 56',
                'kecamatan_id' => $kecamatanIds[array_rand($kecamatanIds)],
                'desa_id' => $desaIds[array_rand($desaIds)],
                'tahun_berdiri' => 2016,
                'jumlah_tenaga_kerja' => 15,
                'omset_tahun' => 80000000,
                'no_telp' => '6281234567894',
                'email' => 'sentimuna@example.com',
                'jenis_badan_usaha' => 'Kelompok',
                'jenis_hki' => 'Hak Cipta',
                'nib' => '123456789012349',
                'facebook' => 'https://facebook.com/sentimuna',
                'instagram' => 'https://instagram.com/sentimuna',
                'tiktok' => 'https://tiktok.com/@sentimuna',
                'whatsapp' => 'https://wa.me/6281234567894',
                'website' => 'https://sentimuna.com',
                'latitude' => -5.3000,
                'longitude' => 122.8000,
                'deskripsi' => 'Grup seni tari yang menampilkan tarian-tarian tradisional Muna dengan sentuhan modern.',
                'status_aktif' => true,
                'status_verifikasi' => true,
                'views' => rand(100, 1000)
            ],
            [
                'nama_usaha' => 'Desain Interior Muda',
                'nama_pemilik' => 'Rina Amelia',
                'subsektor_id' => $subsektorIds[array_rand($subsektorIds)],
                'alamat_usaha' => 'Jl. Arsitek No. 89',
                'kecamatan_id' => $kecamatanIds[array_rand($kecamatanIds)],
                'desa_id' => $desaIds[array_rand($desaIds)],
                'tahun_berdiri' => 2019,
                'jumlah_tenaga_kerja' => 4,
                'omset_tahun' => 300000000,
                'no_telp' => '6281234567895',
                'email' => 'desainmuda@example.com',
                'jenis_badan_usaha' => 'CV',
                'jenis_hki' => null,
                'nib' => '123456789012350',
                'facebook' => 'https://facebook.com/desainmuda',
                'instagram' => 'https://instagram.com/desainmuda',
                'tiktok' => 'https://tiktok.com/@desainmuda',
                'whatsapp' => 'https://wa.me/6281234567895',
                'website' => 'https://desainmuda.com',
                'latitude' => -5.3333,
                'longitude' => 122.8333,
                'deskripsi' => 'Jasa desain interior untuk rumah, kantor, dan ruang komersial dengan gaya modern.',
                'status_aktif' => true,
                'status_verifikasi' => true,
                'views' => rand(100, 1000)
            ],
            [
                'nama_usaha' => 'Studio Foto Muna Vision',
                'nama_pemilik' => 'Fajar Nugroho',
                'subsektor_id' => $subsektorIds[array_rand($subsektorIds)],
                'alamat_usaha' => 'Jl. Kamera No. 12',
                'kecamatan_id' => $kecamatanIds[array_rand($kecamatanIds)],
                'desa_id' => $desaIds[array_rand($desaIds)],
                'tahun_berdiri' => 2020,
                'jumlah_tenaga_kerja' => 3,
                'omset_tahun' => 180000000,
                'no_telp' => '6281234567896',
                'email' => 'munavision@example.com',
                'jenis_badan_usaha' => 'UD',
                'jenis_hki' => null,
                'nib' => '123456789012351',
                'facebook' => 'https://facebook.com/munavision',
                'instagram' => 'https://instagram.com/munavision',
                'tiktok' => 'https://tiktok.com/@munavision',
                'whatsapp' => 'https://wa.me/6281234567896',
                'website' => 'https://munavision.com',
                'latitude' => -5.3667,
                'longitude' => 122.8667,
                'deskripsi' => 'Studio foto profesional untuk berbagai kebutuhan seperti prewedding, event, dan komersial.',
                'status_aktif' => true,
                'status_verifikasi' => true,
                'views' => rand(100, 1000)
            ],
            [
                'nama_usaha' => 'Musik Muda Muna',
                'nama_pemilik' => 'Andi Saputra',
                'subsektor_id' => $subsektorIds[array_rand($subsektorIds)],
                'alamat_usaha' => 'Jl. Harmoni No. 34',
                'kecamatan_id' => $kecamatanIds[array_rand($kecamatanIds)],
                'desa_id' => $desaIds[array_rand($desaIds)],
                'tahun_berdiri' => 2014,
                'jumlah_tenaga_kerja' => 7,
                'omset_tahun' => 250000000,
                'no_telp' => '6281234567897',
                'email' => 'musikmuda@example.com',
                'jenis_badan_usaha' => 'Kelompok',
                'jenis_hki' => 'Hak Cipta',
                'nib' => '123456789012352',
                'facebook' => 'https://facebook.com/musikmuda',
                'instagram' => 'https://instagram.com/musikmuda',
                'tiktok' => 'https://tiktok.com/@musikmuda',
                'whatsapp' => 'https://wa.me/6281234567897',
                'website' => null,
                'latitude' => -5.4000,
                'longitude' => 122.9000,
                'deskripsi' => 'Grup musik lokal yang menciptakan lagu-lagu dengan nuansa budaya Muna.',
                'status_aktif' => true,
                'status_verifikasi' => true,
                'views' => rand(100, 1000)
            ],
            [
                'nama_usaha' => 'Penerbit Buku Muna',
                'nama_pemilik' => 'Lina Sari',
                'subsektor_id' => $subsektorIds[array_rand($subsektorIds)],
                'alamat_usaha' => 'Jl. Literasi No. 56',
                'kecamatan_id' => $kecamatanIds[array_rand($kecamatanIds)],
                'desa_id' => $desaIds[array_rand($desaIds)],
                'tahun_berdiri' => 2021,
                'jumlah_tenaga_kerja' => 2,
                'omset_tahun' => 90000000,
                'no_telp' => '6281234567898',
                'email' => 'penerbitmuna@example.com',
                'jenis_badan_usaha' => 'Perseorangan',
                'jenis_hki' => 'Hak Cipta',
                'nib' => '123456789012353',
                'facebook' => 'https://facebook.com/penerbitmuna',
                'instagram' => 'https://instagram.com/penerbitmuna',
                'tiktok' => 'https://tiktok.com/@penerbitmuna',
                'whatsapp' => 'https://wa.me/6281234567898',
                'website' => 'https://penerbitmuna.com',
                'latitude' => -5.4333,
                'longitude' => 122.9333,
                'deskripsi' => 'Menerbitkan buku-buku lokal yang mengangkat tema budaya dan sejarah Muna Barat.',
                'status_aktif' => true,
                'status_verifikasi' => true,
                'views' => rand(100, 1000)
            ],
            [
                'nama_usaha' => 'Game Studio Muna',
                'nama_pemilik' => 'Rizky Firmansyah',
                'subsektor_id' => $subsektorIds[array_rand($subsektorIds)],
                'alamat_usaha' => 'Jl. Digital No. 78',
                'kecamatan_id' => $kecamatanIds[array_rand($kecamatanIds)],
                'desa_id' => $desaIds[array_rand($desaIds)],
                'tahun_berdiri' => 2022,
                'jumlah_tenaga_kerja' => 5,
                'omset_tahun' => 400000000,
                'no_telp' => '6281234567899',
                'email' => 'gamestudio@example.com',
                'jenis_badan_usaha' => 'CV',
                'jenis_hki' => 'Hak Cipta',
                'nib' => '123456789012354',
                'facebook' => 'https://facebook.com/gamestudio',
                'instagram' => 'https://instagram.com/gamestudio',
                'tiktok' => 'https://tiktok.com/@gamestudio',
                'whatsapp' => 'https://wa.me/6281234567899',
                'website' => 'https://gamestudio.com',
                'latitude' => -5.4667,
                'longitude' => 122.9667,
                'deskripsi' => 'Mengembangkan game-game edukatif dan hiburan yang mengangkat budaya lokal.',
                'status_aktif' => true,
                'status_verifikasi' => true,
                'views' => rand(100, 1000)
            ]
        ];

        foreach ($umkms as $umkm) {
            UMKM::create($umkm);
        }
    }
}
